### ISSUE TITLE
Renderer to renderer: cannot reply

### ISSUE THREAD

**Issue by KoltesDigital** [electron-utils/electron-ipc-plus#4]
Hi,

When sending a message through `sendToWins`, the receiving handler cannot reply. Is it intended? Too bad because it would make the communication between two windows easier.

Cheers

**Comment by jwu** [comment]
Hi @KoltesDigital ,

I guess you forget to `require('electron-ipc-plus')` in main process when you start your app. I met the same problem before. 

I still not have good way to solve it, so I think i should put some warning message for this. Can you confirm this, can send me an example if my solution not solve it.

**Comment by KoltesDigital** [comment]
Actually it is! For a simple reason: I have to wait that both windows are ready. I prepared for you an excerpt of my project at <https://github.com/KoltesDigital/electron-ipc-plus-bug-renderer-to-renderer>. If you launch it, you'll see that the display window receives the message from the control wlindow, but cannot reply. In case you wonder, in the actual project, I have other dependencies, therefore I can't base on the usual event `did-finish-load` to know that the script is initialized.

**Comment by jwu** [comment]
I check your code, and you are using `ipcPlus.sendToWins` and wait for reply from it. Actually this will not happen. All broadcast message such as `sendToAll`, `sendToWins` will not receive callback, because it doesn't know how much callback should it receive and when should it close the callback session.

**Comment by KoltesDigital** [comment]
Agreed on the broadcast. So in my project I have written an explicit renderer -> main -> renderer communication, where the first message argument is the target name, and the rest is forwarded, so the second argument sent is actually the first one (channel) in the receiving target. I still think the feature renderer -> renderer would be interesting to have out of the box though, i.e. that your library could handle this relay for the user, but this implies being able to distinguish and address specific renderers.

Staying at a broadcast level, you could use what you already have: the first call to `event.reply` is taken into account, the others are ignored. Or perhaps you can add a new feature for broadcast messages, that the callback can be called once per target.

If it stays like it is now, I can't tell for the warning, but a note in the API references would be useful.

**Comment by jwu** [comment]
I leave the renderer2renderer for user because I think different project have different way to manage windows (by name, by ID, ...). So I design the library to make it only do the essential thing and don't grow too big. 

There is an example project I think you can reference for renderer2renderer process: https://github.com/electron-utils/electron-panel/blob/master/docs/panel-renderer.md#panelsend-panelid-message-args-callback-timeout The panel here use the `panel-id` for communication, and the implementation in it is actually a renderer -> main -> renderer process. Maybe this can help u implement your version of `send2win`.

For API reference, actually the callback parameter only show in https://github.com/electron-utils/electron-ipc-plus/blob/master/docs/ipc-renderer.md#ipcplusrsendtomainmessage-args-callback-timeout, and you can see the `sendToWins` didn't have a callback parameter in it. But i agree I should add a note in the API to make it clear.

**Comment by KoltesDigital** [comment]
I went for a simpler approach, only using your public API, merely merging the two snippets of your Readme. I agree electron-panel can handle an unlimited number of targets, but I don't need this complexity.

> it is hard to remember reply the event when project become complex

Surely, but I think this problem also happens even if you're managing explicitly the relay. So it's more a problem of project organization, which is out of scope of the library.

Anyway, thanks for the discussion!
